=== EagleGlimpse/vrjuggler/juggler/modules/tweek/java/beanlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="beanlist">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:choice>
          <xs:element name="service"  type="basicBean" />
          <xs:element name="viewer"   type="basicBean" />
          <xs:element name="guipanel" type="guiBean" />
          <xs:element name="generic"  type="basicBean" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="basicBean">
    <xs:sequence>
      <xs:element name="file"       type="beanFile" />
      <xs:element name="dependency" type="beanDep" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="guiBean">
    <xs:complexContent>
      <xs:extension base="basicBean">
        <xs:sequence>
          <xs:element name="tree">
            <xs:complexType>
              <xs:attribute name="path" type="treePath" use="optional"
                            default="/" />
            </xs:complexType>
          </xs:element>
          <xs:element name="icon" minOccurs="0">
            <xs:complexType>
              <xs:attribute name="source"  type="xs:anyURI" use="required" />
              <xs:attribute name="tooltip" type="xs:string" use="optional"
                            default="" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="beanFile">
    <xs:attribute name="name"  type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="beanDep">
    <xs:attribute name="file" type="xs:string" />
    <xs:attribute name="path" type="xs:string" />
  </xs:complexType>

  <xs:simpleType name="treePath">
    <xs:restriction base="xs:string">
      <xs:pattern value="/(|\w[\w\s]*(/\w[\w\s]*)*)" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== EagleGlimpse/vrjuggler/modules/vrjuggler/vrjconfig/VRJConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<beanlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://www.vrjuggler.org/tweek/beanlist.xsd">
   <guipanel name="VRJConfig">
      <file name="${TWEEK_BASE_DIR}/bin/beans/VRJConfig.jar"
            class="org.vrjuggler.vrjconfig.VrjConfig" />
      <dependency file="jccl_config.jar" path="${TWEEK_BASE_DIR}/bin/beans" />
      <dependency file="jccl_editors.jar" path="${TWEEK_BASE_DIR}/bin/beans" />
      <tree path="/" />
   </guipanel>

   <guipanel name="ControlPanel">
      <file name="${TWEEK_BASE_DIR}/bin/beans/VRJConfig.jar"
            class="org.vrjuggler.vrjconfig.ControlPanelView" />
      <dependency file="jccl_config.jar" path="${TWEEK_BASE_DIR}/bin/beans" />
      <dependency file="jccl_editors.jar" path="${TWEEK_BASE_DIR}/bin/beans" />
      <dependency file="ui.jar" path="${TWEEK_BASE_DIR}/bin" />
      <tree path="/" />
   </guipanel>
</beanlist>
